### ISSUE TITLE
Error when `.swift-version` contains a newline

### ISSUE THREAD

**Issue by PadraigK** [PadraigK/swiftformat-nova#1]
> Isaac: I’m seeing an error when I try to use the extension, saying it can’t find the SwiftLint executable. I have confirmed that the executable does in fact exist at that path. Any ideas what might be going on?

![image](https://github.com/PadraigK/swiftformat-nova/assets/466150/6cb15903-0493-4a35-be29-3f24379e54e6)

![image](https://github.com/PadraigK/swiftformat-nova/assets/466150/fa73819d-76b4-4946-a49c-155d8cb2b025)

https://allamaraine.io/@hisaac/111098650820462874

**Comment by PadraigK** [comment]
cc: @hisaac

**Comment by PadraigK** [comment]
Ah, this happens if there's a newline in the `.swift-version` file

**Comment by hisaac** [comment]
Strange! Thanks for the quick fix 🙏
